//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univercity.Models.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_manager_group
    {
        public string code_national_teacher { get; set; }
        public Nullable<int> code_group_lesson { get; set; }
        public string name_user { get; set; }
        public string password { get; set; }
        public Nullable<bool> code_status_account { get; set; }
    }
}
