//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univercity.Models.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_project
    {
        public int code_project { get; set; }
        public Nullable<int> code_group_lesson { get; set; }
        public string code_supervisor { get; set; }
        public Nullable<System.DateTime> date_request_project { get; set; }
        public Nullable<System.DateTime> date_completion_project { get; set; }
        public string title_project { get; set; }
        public string code_type_subject_project { get; set; }
        public string description_project { get; set; }
        public Nullable<bool> status_accept_partner { get; set; }
        public Nullable<bool> status_accept_supervisor { get; set; }
        public Nullable<bool> status_accept_manager_group { get; set; }
    }
}
