//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univercity.Models.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_subject_proposed
    {
        public string code_national_teacher { get; set; }
        public Nullable<int> code_group_lesson { get; set; }
        public string title_project { get; set; }
        public string type_subject_project { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> date_register_infirmation { get; set; }
    }
}
