//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univercity.Models.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_teacher_record_edu
    {
        public string code_national_teacher { get; set; }
        public Nullable<int> code_grade { get; set; }
        public string major { get; set; }
        public Nullable<decimal> avg_each_grade { get; set; }
        public string uni_edu { get; set; }
        public string country_edu { get; set; }
        public Nullable<System.DateTime> date_start_grade { get; set; }
        public Nullable<System.DateTime> date_end_grade { get; set; }
        public Nullable<System.DateTime> date_register_information { get; set; }
    }
}
