//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univercity.Models.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_teacher_period_language_computer
    {
        public string code_national_teacher { get; set; }
        public string name_priod { get; set; }
        public string level_period { get; set; }
        public string place_period_edu { get; set; }
        public Nullable<System.DateTime> year { get; set; }
        public Nullable<int> hours_period { get; set; }
        public Nullable<System.DateTime> date_register_information { get; set; }
    }
}
