//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univercity.Models.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_teacher_information_spouse
    {
        public string code_national_teacher { get; set; }
        public string name_spouse { get; set; }
        public string family_spouse { get; set; }
        public Nullable<bool> code_national { get; set; }
        public string name_country { get; set; }
        public Nullable<int> code_religion_din { get; set; }
        public Nullable<int> code_religion_mazhab { get; set; }
        public string place_birth { get; set; }
        public Nullable<System.DateTime> date_register_information { get; set; }
    }
}
