//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univercity.Models.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_project_member
    {
        public int code_project { get; set; }
        public string code_student { get; set; }
        public Nullable<bool> code_type_member { get; set; }
        public Nullable<decimal> score_referee { get; set; }
        public Nullable<decimal> score_supervisor { get; set; }
        public Nullable<decimal> score_final { get; set; }
        public Nullable<bool> code_status_final { get; set; }
        public byte[] file_project { get; set; }
    }
}
