//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univercity.Models.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_teacher_reference
    {
        public string code_national_teacher { get; set; }
        public string name { get; set; }
        public string family { get; set; }
        public string type_relationship_familiarity { get; set; }
        public string time_acqu { get; set; }
        public string job { get; set; }
        public string address_place_work { get; set; }
        public string phone_number { get; set; }
        public Nullable<int> code_type_reference { get; set; }
        public Nullable<System.DateTime> date_register_information { get; set; }
    }
}
