//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univercity.Models.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_supervisor
    {
        public string code_national_teacher { get; set; }
        public Nullable<int> code_group_lesson { get; set; }
        public Nullable<System.DateTime> date_choosen_supervisor { get; set; }
        public Nullable<System.DateTime> date_complation_supervisor { get; set; }
        public Nullable<int> capacity_people { get; set; }
        public Nullable<int> capacity_remaining_people { get; set; }
        public Nullable<int> capacity_title { get; set; }
        public Nullable<int> capacity_remaining_title { get; set; }
        public string description { get; set; }
        public string name_user { get; set; }
        public Nullable<System.DateTime> date_register_information { get; set; }
    }
}
