//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univercity.Models.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_student_personal_information
    {
        public string code_student { get; set; }
        public string name_student { get; set; }
        public string family_student { get; set; }
        public Nullable<System.DateTime> date_birth { get; set; }
        public Nullable<int> sex { get; set; }
        public string major_student { get; set; }
        public string grade { get; set; }
        public string type_training_system { get; set; }
        public string code_natinal_student { get; set; }
        public string phone_number { get; set; }
        public string email_student { get; set; }
        public string address_student { get; set; }
    }
}
