//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEmployee
    {
        public int ID { get; set; }
        public Nullable<int> FkUser { get; set; }
        public Nullable<System.DateTime> DateResponce { get; set; }
        public string TypeLeave { get; set; }
        public Nullable<System.TimeSpan> FromTime { get; set; }
        public Nullable<System.TimeSpan> ToTime { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string PersonelAlter { get; set; }
        public string Description { get; set; }
        public Nullable<bool> ConfirmDeputy { get; set; }
        public Nullable<bool> ConfirmAdmin { get; set; }
    
        public virtual TblUser TblUser { get; set; }
    }
}
