//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Users
    {
        public int ID { get; set; }
        public string PersonelID { get; set; }
        public string FullName { get; set; }
        public string CodeMelli { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string Uname { get; set; }
        public string Upass { get; set; }
        public string IsAdmin { get; set; }
    }
}
