//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univercity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_project_report
    {
        public int code { get; set; }
        public Nullable<int> Fk_code_student { get; set; }
        public Nullable<int> Fk_code_project { get; set; }
        public string date_report { get; set; }
        public string text_report { get; set; }
        public Nullable<int> Fk_code_month { get; set; }
    }
}
