//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univercity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_teacher_article_research
    {
        public int code { get; set; }
        public string code_national_teacher { get; set; }
        public Nullable<int> code_type_reserch { get; set; }
        public string name { get; set; }
        public string title_conference { get; set; }
        public Nullable<int> code_type_conference { get; set; }
        public Nullable<System.DateTime> date_start_reserch { get; set; }
        public Nullable<System.DateTime> date_end_reserch { get; set; }
        public Nullable<System.DateTime> date_release { get; set; }
        public string name_author { get; set; }
        public string nameandaddress_location_print { get; set; }
    }
}
