//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univercity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_student_graduated
    {
        public string code_student { get; set; }
        public Nullable<int> code_state { get; set; }
        public Nullable<int> code_city { get; set; }
        public string name_place_work { get; set; }
        public string phone_place_work { get; set; }
        public string address_place_work { get; set; }
        public byte[] file_documentation { get; set; }
    }
}
