//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univercity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_status_accept_partner_show
    {
        public bool code_status_accept_partner { get; set; }
        public string code_status_accept_partner_show { get; set; }
    }
}
