//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univercity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_record_professional
    {
        public int code { get; set; }
        public string code_national_teacher { get; set; }
        public string name_company_or_organization { get; set; }
        public string official { get; set; }
    }
}
