//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univercity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_supervisor
    {
        public string code_national_teacer { get; set; }
        public string code_group_lesson { get; set; }
        public string date_chosen_supervisor { get; set; }
        public string date_complation_supervisor { get; set; }
        public Nullable<int> capacity_people { get; set; }
        public Nullable<int> capacity_remaining_people { get; set; }
        public string capacity_remaining_title { get; set; }
        public Nullable<int> capacity_title { get; set; }
        public string description { get; set; }
    }
}
