//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univercity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_show_type_subject_project
    {
        public int code_type_subject_project { get; set; }
        public Nullable<int> code_group_lesson { get; set; }
        public string code_type_subject_project_show { get; set; }
    }
}
