//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univercity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_adminstrator
    {
        public string name_user { get; set; }
        public string password { get; set; }
        public string name_user_show { get; set; }
        public Nullable<int> level_access { get; set; }
        public Nullable<bool> status_account { get; set; }
    }
}
