//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univercity.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class univercityEntities : DbContext
    {
        public univercityEntities()
            : base("name=univercityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_adminstrator> tbl_adminstrator { get; set; }
        public virtual DbSet<tbl_group_lesson> tbl_group_lesson { get; set; }
        public virtual DbSet<tbl_manager_group> tbl_manager_group { get; set; }
        public virtual DbSet<tbl_project> tbl_project { get; set; }
        public virtual DbSet<tbl_project_member> tbl_project_member { get; set; }
        public virtual DbSet<tbl_project_report> tbl_project_report { get; set; }
        public virtual DbSet<tbl_show_city> tbl_show_city { get; set; }
        public virtual DbSet<tbl_show_grade> tbl_show_grade { get; set; }
        public virtual DbSet<tbl_show_group_lesson> tbl_show_group_lesson { get; set; }
        public virtual DbSet<tbl_show_level_access> tbl_show_level_access { get; set; }
        public virtual DbSet<tbl_show_month> tbl_show_month { get; set; }
        public virtual DbSet<tbl_show_national> tbl_show_national { get; set; }
        public virtual DbSet<tbl_show_occupation> tbl_show_occupation { get; set; }
        public virtual DbSet<tbl_show_quotas> tbl_show_quotas { get; set; }
        public virtual DbSet<tbl_show_religion_din> tbl_show_religion_din { get; set; }
        public virtual DbSet<tbl_show_religion_mazhab> tbl_show_religion_mazhab { get; set; }
        public virtual DbSet<tbl_show_sex> tbl_show_sex { get; set; }
        public virtual DbSet<tbl_show_state> tbl_show_state { get; set; }
        public virtual DbSet<tbl_show_student_extended_project> tbl_show_student_extended_project { get; set; }
        public virtual DbSet<tbl_show_type_activity_teacher> tbl_show_type_activity_teacher { get; set; }
        public virtual DbSet<tbl_show_type_conference> tbl_show_type_conference { get; set; }
        public virtual DbSet<tbl_show_type_cooperation> tbl_show_type_cooperation { get; set; }
        public virtual DbSet<tbl_show_type_member> tbl_show_type_member { get; set; }
        public virtual DbSet<tbl_show_type_reference_teacher> tbl_show_type_reference_teacher { get; set; }
        public virtual DbSet<tbl_show_type_research> tbl_show_type_research { get; set; }
        public virtual DbSet<tbl_show_type_subject_project> tbl_show_type_subject_project { get; set; }
        public virtual DbSet<tbl_status_accept_manager_group_show> tbl_status_accept_manager_group_show { get; set; }
        public virtual DbSet<tbl_status_accept_partner_show> tbl_status_accept_partner_show { get; set; }
        public virtual DbSet<tbl_status_accept_supervisor_show> tbl_status_accept_supervisor_show { get; set; }
        public virtual DbSet<tbl_status_account_show> tbl_status_account_show { get; set; }
        public virtual DbSet<tbl_status_duty_system_show> tbl_status_duty_system_show { get; set; }
        public virtual DbSet<tbl_status_employment_show> tbl_status_employment_show { get; set; }
        public virtual DbSet<tbl_status_final_show> tbl_status_final_show { get; set; }
        public virtual DbSet<tbl_status_marrid_show> tbl_status_marrid_show { get; set; }
        public virtual DbSet<tbl_status_occupation_show> tbl_status_occupation_show { get; set; }
        public virtual DbSet<tbl_status_select_project_student_show> tbl_status_select_project_student_show { get; set; }
        public virtual DbSet<tbl_status_student> tbl_status_student { get; set; }
        public virtual DbSet<tbl_student_graduated> tbl_student_graduated { get; set; }
        public virtual DbSet<tbl_student_personal_information> tbl_student_personal_information { get; set; }
        public virtual DbSet<tbl_subject_proposed> tbl_subject_proposed { get; set; }
        public virtual DbSet<tbl_supervisor> tbl_supervisor { get; set; }
        public virtual DbSet<tbl_teacher_article_research> tbl_teacher_article_research { get; set; }
        public virtual DbSet<tbl_teacher_honor> tbl_teacher_honor { get; set; }
        public virtual DbSet<tbl_teacher_information_spouse> tbl_teacher_information_spouse { get; set; }
        public virtual DbSet<tbl_teacher_invention> tbl_teacher_invention { get; set; }
        public virtual DbSet<tbl_teacher_period_language_computer> tbl_teacher_period_language_computer { get; set; }
        public virtual DbSet<tbl_teacher_presonal_information> tbl_teacher_presonal_information { get; set; }
        public virtual DbSet<tbl_teacher_quotas> tbl_teacher_quotas { get; set; }
        public virtual DbSet<tbl_teacher_record_edu> tbl_teacher_record_edu { get; set; }
        public virtual DbSet<tbl_teacher_record_edu_academic> tbl_teacher_record_edu_academic { get; set; }
        public virtual DbSet<tbl_teacher_record_employment> tbl_teacher_record_employment { get; set; }
        public virtual DbSet<tbl_teacher_record_professional> tbl_teacher_record_professional { get; set; }
        public virtual DbSet<tbl_teacher_reference> tbl_teacher_reference { get; set; }
        public virtual DbSet<tbl_record_professional> tbl_record_professional { get; set; }
    }
}
